# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest
import HtmlTestRunner


class TestAPAANNIH(unittest.TestCase):

    def setUp(self) :
        self.driver = webdriver.Chrome(executable_path="C:\chromedriver_win32\chromedriver.exe")
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_aPAANNIH(self):
        # Test name: APAANNIH
        # Step # | name | target | value
        # 1 | open | http://testautomationpractice.blogspot.com/ |
        self.driver.get("http://testautomationpractice.blogspot.com/")
        # 2 | setWindowSize | 1266x674 |
        self.driver.set_window_size(1266, 674)
        # 3 | selectFrame | index=0 |
        self.driver.switch_to.frame(0)
        # 4 | click | id=RESULT_TextField-1 |
        self.driver.find_element(By.ID, "RESULT_TextField-1").click()
        # 5 | type | id=RESULT_TextField-1 | APA HAYOOO
        self.driver.find_element(By.ID, "RESULT_TextField-1").send_keys("APA HAYOOO")
        # 6 | click | id=RESULT_TextField-2 |
        self.driver.find_element(By.ID, "RESULT_TextField-2").click()
        # 7 | type | id=RESULT_TextField-2 | AKHIR
        self.driver.find_element(By.ID, "RESULT_TextField-2").send_keys("AKHIR")
        # 8 | type | id=RESULT_TextField-3 | TELEFONEE
        self.driver.find_element(By.ID, "RESULT_TextField-3").send_keys("TELEFONEE")
        # 9 | click | id=RESULT_TextField-4 |
        self.driver.find_element(By.ID, "RESULT_TextField-4").click()
        # 10 | type | id=RESULT_TextField-4 | APA AAN TUH
        self.driver.find_element(By.ID, "RESULT_TextField-4").send_keys("APA AAN TUH")
        # 11 | click | id=q6 |
        self.driver.find_element(By.ID, "q6").click()
        # 12 | click | id=RESULT_TextField-5 |
        self.driver.find_element(By.ID, "RESULT_TextField-5").click()
        # 13 | type | id=RESULT_TextField-5 | Jakarta
        self.driver.find_element(By.ID, "RESULT_TextField-5").send_keys("Jakarta")
        # 14 | click | id=RESULT_TextField-6 |
        self.driver.find_element(By.ID, "RESULT_TextField-6").click()
        # 15 | type | id=RESULT_TextField-6 | T
        self.driver.find_element(By.ID, "RESULT_TextField-6").send_keys("T")
        # 16 | click | css=.form_table |
        self.driver.find_element(By.CSS_SELECTOR, ".form_table").click()


if __name__ == '_main_':
    unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output="C:\\Users\\NB01\\PycharmProjects\\HelloWorld\\Reports"))